ENCODER_MAP_ENABLE = no

VIA_ENABLE = yes
TAP_DANCE_ENABLE = no
BOOTMAGIC_ENABLE = yes # Enable Bootmagic Lite
EXTRAKEY_ENABLE = yes # Enable extra keys
INVERT_NUMLOCK_INDICATOR = no
STARTUP_NUMLOCK_ON = no
MOUSEKEY_ENABLE = no